# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: pre-commit autoupdate  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: search-and-replace
        args: [--search, 'PySide6', --replacement, 'PySide']
    -   id: search-and-replace
        args: [--search, 'PySide2', --replacement, 'PySide']
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
