# .pre-commit-config.yaml
repos:
-   repo: https://github.com/mattlqx/pre-commit-search-and-replace
    rev: v1.1.2
    hooks:
    -   id: search-and-replace
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.1.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
